# -*- coding: utf-8 -*-
"""Use the embedding generated by a trained GNN as feature"""
from matminer.featurizers.base import BaseFeaturizer


# Using MEGNet seems to be the most efficient way to do this.
class ElectronicMEGNet(BaseFeaturizer):
    ...
